function show(){
  document.getElementById("about").classList.add("content")
  document.getElementById("about-body").classList.add("content")
  document.getElementById("contact").classList.add("content")
  document.getElementById("contact-gh").classList.add("content")
  document.getElementById("contact-ln").classList.add("content")
  document.getElementById("contact-email").classList.add("content")
  document.getElementById("contact-phone").classList.add("content")
  document.getElementById("apps").classList.add("content-apps")
  document.getElementById("contact").classList.remove("d-none")
  document.getElementById("contact-gh").classList.remove("d-none")
  document.getElementById("contact-ln").classList.remove("d-none")
  document.getElementById("contact-email").classList.remove("d-none")
  document.getElementById("contact-phone").classList.remove("d-none")
  document.getElementById("apps").classList.remove("d-none")
  document.getElementById("about").classList.remove("d-none")
  document.getElementById("about-body").classList.remove("d-none")

  document.getElementById("app-title").classList.add("content")
  document.getElementById("kotini").classList.add("content")
  document.getElementById("kotini-body").classList.add("content")
  document.getElementById("kannedit").classList.add("content")
  document.getElementById("kannedit-body").classList.add("content")
  document.getElementById("vaultman").classList.add("content")
  document.getElementById("vaultman-body").classList.add("content")
  document.getElementById("bugbyte").classList.add("content")
  document.getElementById("bugbyte-body").classList.add("content")
  document.getElementById("bugbyte-img").classList.add("content")

}